// Precompiles the prelude and doc assets into TS string constants (src/assets.generated.ts), so the package
// needs no text-import attribute and its dist carries the texts. Runs first in `build`; `test/assets.test.ts`
// fails when the committed module drifts from the assets.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageDir = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Generated constant name -> asset path relative to the package root. */
const ASSETS: Readonly<Record<string, string>> = {
	COMPUTER_PRELUDE_JAVASCRIPT: "src/prelude.js",
	COMPUTER_PRELUDE_PYTHON: "src/prelude.py",
	COMPUTER_DECLARATIONS: "declarations.d.ts",
	COMPUTER_DOCUMENTATION: "docs/computer.md",
	COMPUTER_SAFETY: "docs/computer-safety.md",
};

export const ASSETS_MODULE_PATH = join(packageDir, "src/assets.generated.ts");

/** A JS string literal quoted the way biome formats it: single quotes only when that needs fewer escapes. */
function stringLiteral(text: string): string {
	const json = JSON.stringify(text);
	if (text.split('"').length <= text.split("'").length) return json;
	const body = json.slice(1, -1).replace(/\\.|'/g, (token) => (token === '\\"' ? '"' : token === "'" ? "\\'" : token));
	return `'${body}'`;
}

export function renderAssetsModule(): string {
	const constants = Object.entries(ASSETS).map(([name, path]) => {
		const text = readFileSync(join(packageDir, path), "utf8");
		return `/** Text of \`${path}\`. */\nexport const ${name} =\n\t${stringLiteral(text)};\n`;
	});
	const header =
		"// GENERATED by scripts/generate-assets.ts from the prelude and doc assets.\n" +
		"// Do not edit by hand; run `bun run --cwd packages/senpi-desktop-prelude generate`.\n" +
		"// biome-ignore-all lint/suspicious/noTemplateCurlyInString: the constants hold JavaScript source text verbatim.\n";
	return [header, ...constants].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	writeFileSync(ASSETS_MODULE_PATH, renderAssetsModule());
}
